services:
  postgres:
    image: 'postgis/postgis:17-3.5'
    environment:
      - 'POSTGRES_USER=jumbo'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=jumbo'
      - 'url=jdbc:postgresql://postgres:5432/jumbo'
      - 'SPRING_DATASOURCE_URL = jdbc:postgresql://postgres:5432/jumbo'
    ports:
      - '5432:5432'
