server:
  port: 8980

spring:
  application:
    name: jumbo-locator
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jumbo}
    username: ${DB_USER:jumbo}
    password: ${DB_PASSWORD:secret}
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
